[package]
name = "b2b-prototype-backend"
version = "0.1.0"
authors = ["Florian Liesegang <lysigk@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
env_logger = "0.8"
futures = "0.3"
log = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
